"""
Constants for the quantitative trading system.
"""

# Trading directions
DIRECTION_LONG = 1
DIRECTION_SHORT = -1
DIRECTION_NULL = 0

# Order types
ORDER_TYPE_MARKET = "MARKET"
ORDER_TYPE_LIMIT = "LIMIT"
ORDER_TYPE_STOP = "STOP"

# Order status
ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_SUBMITTED = "SUBMITTED"
ORDER_STATUS_FILLED = "FILLED"
ORDER_STATUS_CANCELLED = "CANCELLED"
ORDER_STATUS_REJECTED = "REJECTED"

# System modes
MODE_BACKTEST = "backtest"
MODE_PAPER = "paper"
MODE_LIVE = "live"

# Data frequencies
FREQ_TICK = "TICK"
FREQ_MINUTE = "1MIN"
FREQ_5MIN = "5MIN"
FREQ_15MIN = "15MIN"
FREQ_30MIN = "30MIN"
FREQ_HOUR = "1H"
FREQ_DAILY = "DAILY"
FREQ_WEEKLY = "WEEKLY"
FREQ_MONTHLY = "MONTHLY"

# Market status
MARKET_OPEN = "OPEN"
MARKET_CLOSE = "CLOSE"
MARKET_HALT = "HALT"

# Signal confidence levels
CONFIDENCE_HIGH = 0.8
CONFIDENCE_MEDIUM = 0.5
CONFIDENCE_LOW = 0.3
